development:
  adapter: postgresql
  encoding: unicode
  database: SurfboardApp_development
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: SurfboardApp_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: SurfboardApp_production
  pool: 5

